image: ros:indigo-ros-base
build:
  stage: build

  before_script: 
     - apt update && apt install build-essential ros-indigo-tf -y
     - mkdir -p catkin_ws/src
     - cd catkin_ws/src
     - catkin_init_workspace
     - cd ../..
     - cp -r robohub_object_tracking catkin_ws/src
     - cd catkin_ws
     - catkin_make
     - source devel/setup.bash
     - ls
     - env | grep PYTHON
  script: 
    - rostest robohub_object_tracking run_tests.test

# run tests using the binary built before
#test:
#  stage: test
#  script:
#    - ./runmytests.sh